[package]
name = "embedding"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
eyre = "0.6.12"
reqwest = { version = "0.12.23", features = ["json"] }
serde_json = "1.0.143"
thiserror = "2.0.16"
