[package]
name = "daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
daemonize = "0.5.0"
interprocess = "2.2.3"

embedding = { path = "../embedding" }
storage_client = { path = "../storage_client" }
eyre = "0.6.12"
